# Generated by Django 4.2 on 2023-04-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
